#sftp params mapping with actul prams
sftp:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: filePath
#mysql params mapping with actul prams
mysql:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
  param6: dbUrl
  param7: driverClassName
  param8: driverLoaction
#clickhouse params mapping with actul prams
clickhouse:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
  param6: dbUrl
  param7: driverClassName
  param8: driverLoaction
#mssql params mapping with actul prams
mssql:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
  param6: dbUrl
  param7: driverClassName
  param8: driverLoaction
#postgres params mapping with actul prams
postgres:
  param1: userName
  param2: host
  param3: port
  param4: password
  param5: dbName
  param6: dbUrl
  param7: driverClassName
  param8: driverLoaction